services:
  mt5:    
    build:
      dockerfile: Dockerfile
    image: mt5_v2
    container_name: mt5_v2
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 8001:8001
      - 7171:7171
    env_file:
      - .env
    restart: unless-stopped
